labels:

  - label: "ci"
    type: pull_request
    title: '^ci(?:\(.+\))?\!?:'
    files:
      - '\.github/.+'

      # Type: Documentation changes
  -   label: "@type/docs"
      title: '^docs(?:\(.+\))?\!?:'

    # Type: New feature
  -   label: "@type/feature"
      title: '^feat(?:\(.+\))?\!?:'

    # Type: Bug fix
  -   label: "@type/fix"
      title: '^fix(?:\(.+\))?\!?:'

    # Type: Improvements such as style changes, refactoring, or performance improvements
  -   label: "@type/enhancement"
      title: '^(style|refactor|perf)(?:\(.+\))?\!?:'

    # Issue Type Only: Feature Request
  -   label: "Feature Request"
      type: issue
      title: "^(Feature Request|\\[FEAT\\])"

    # Issue Type Only: Documentation
  -   label: "Documentation"
      type: issue
      title: "^.*(\b[Dd]ocumentation|doc(s)?\b).*"

    # Issue Type Only: Bug Report
  -   label: "Bug Report"
      type: issue
      title: "^.*(\b[Bb]ug|b(u)?g(s)?\b).*"
