name: Bug Report
description: State if something is wrong
title: "[BUG]: <TITLE>"
labels: ["bug", "important", 'needs-triage']
assignees:
  - DrKJeff16

body:
  - type: checkboxes
    attributes:
      label: Issue Checks
      description: "Make sure to read every checkbox and answer truthfully:"
      options:
        - label: I am running on the latest version of `project.nvim`
          required: true
        - label: I have checked for existing issues related to this one, whether open or closed
          required: true
        - label: I have read the docs (`README.md`, `:h project-nvim`, etc.), and also the ones for `telescope.nvim`
          required: true

  - type: checkboxes
    attributes:
      label: What is the problem you encountered relate to?
      description: "Check one or more types of concepts your issue relates to:"
      options:
        - label: The plugin is not detecting directories correctly
          required: false
        - label: The plugin is not changing directories
          required: false
        - label: Logging issues
          required: false
        - label: Another plugin interferes with `project.nvim`
          required: false
        - label: Project history broke
          required: false
        - label: The Telescope picker is having issues
          required: false
        - label: Windows is causing undesirable behaviour
          required: false
        - label: Documentation needs a revision
          required: false
        - label: Other
          required: false

  - type: input
    attributes:
      label: "What neovim version are you using? (`nvim -v`)"
      placeholder: "v0.12.0-dev-839+ga08d6a8ac1"
    validations:
      required: true

  - type: input
    attributes:
      label: "Operating system and, if possible, what version?"
      placeholder: Linux 6.15.6-arch1-1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: Write down what happened, as detailed as you can. Avoid irrelevant info
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe clearly what were you expecting to occur
    validations:
      required: true

  - type: textarea
    attributes:
      label: Output of `:checkhealth project`
      description: If you can run `project.nvim`, run `:checkhealth project` and paste the output.
      placeholder: "<PASTE HERE IF POSSIBLE>"
    validations:
      required: false

  - type: textarea
    attributes:
      label: How did you setup the plugin?
      description: Paste the relevant code snippet of how you configured this plugin
      value: |
        require("lazy").setup({
          spec = {
            {
              'DrKJeff16/project.nvim',
              version = false,
              config = function()
                require('project_nvim').setup(...)
              end,
            },
          },
        })
      render: lua
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Info and/or Screenshots
      description: If there's more info you could tell, please do. Screenshots too, if applicable
    validations:
      required: false
