name: Action Release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  merge_group:
    branches:
      - main
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v5
      - name: Build project assets
        id: checkout
        run: |
          mkdir -pv project.nvim
          cp -rv lua doc plugin README.md LICENSE project.nvim
          zip -r -9 project.nvim.zip project.nvim
          tar cvJf project.nvim.tar.xz project.nvim
          sha512sum project.nvim.zip > project.nvim.zip.sha512sum
          sha512sum project.nvim.tar.xz > project.nvim.tar.xz.sha512sum
          rm -rfv project.nvim

      - name: Get Release
        id: get_current_release
        uses: joutvhu/get-release@v1.0.3
        with:
          # Should get latest release?
          latest: true
          # Find the latest release including the pre-releases
          prerelease: true
          # A pattern string to filter the releases by tag_name
          pattern: '^v.*'
          # Show ouputs
          debug: true
          # Fail when no release was found
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release File
        run: echo ${{ github.sha }} > Release.txt
      - name: Test Release
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            project.nvim.tar.xz
            project.nvim.tar.xz.sha512sum
            project.nvim.zip
            project.nvim.zip.sha512sum
          token: ${{ secrets.GITHUB_TOKEN }}
