name: Greetings

on:
  pull_request_target:
    branches:
      - main
  issues:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "(AUTOMATED): Thank you for your feedback. Your issue will be adressed ASAP, if it is legitimate"
        pr-message: "(AUTOMATED): Many many thanks for your contributions! Your PR will be checked ASAP"
