name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greetings:
    name: Give First-Time Contributors a Greeting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          ## Greetings:

          Thank you for your feedback. If your issue is deemed legitimate will be adressed **ASAP**.
        pr-message: |
          ## Greetings:

          Many many thanks for your contributions! Your PR will be checked ASAP.
