name: Labeler

on:
  - discussion
  - issues
  - pull_request
  - pull_request_review
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your code
      uses: actions/checkout@v5

    - name: Run Labeler
      uses: srvaroa/labeler@master
      with:
        fail_on_error: false
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
