name: Luacheck

permissions:
  contents: read

on:
  - push
  - pull_request

env:
  CLICOLOR: 1

jobs:
  luacheck:
    name: Lint Lua files using Luacheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: lua
