name: pre-commit

on:
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6

      - uses: pre-commit/action@v3.0.1
